services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: Kairodb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kairo_api
    restart: always
    ports:
      - "3000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mariadb

volumes:
  mariadb_data: