// <auto-generated />
using KairoApi.Db.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KairoApi.Db.Migrations
{
    [DbContext(typeof(KairoApiDbContext))]
    [Migration("20260509141745_1.0.3")]
    partial class _103
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KairoApi.Model.LKP.LKP_StatusDao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("LKP_KairoApi_Status");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "To do"
                        },
                        new
                        {
                            id = 2,
                            Name = "Doing"
                        },
                        new
                        {
                            id = 3,
                            Name = " In Review"
                        },
                        new
                        {
                            id = 4,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("KairoApi.Model.TaskDao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LKP_StatusDaoid")
                        .HasColumnType("int");

                    b.Property<int?>("StatusDaoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("id");

                    b.HasIndex("LKP_StatusDaoid");

                    b.ToTable("KairoApi_Task");
                });

            modelBuilder.Entity("KairoApi.Model.UserDao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("KairoApi_User");
                });

            modelBuilder.Entity("KairoApi.Model.TaskDao", b =>
                {
                    b.HasOne("KairoApi.Model.LKP.LKP_StatusDao", "LKP_StatusDao")
                        .WithMany()
                        .HasForeignKey("LKP_StatusDaoid");

                    b.Navigation("LKP_StatusDao");
                });
#pragma warning restore 612, 618
        }
    }
}
