<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>7586ab3b-e4f7-4cdf-9543-3eaa70ca8388</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.15">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\KairoApi.Business\KairoApi.Business.csproj" />
	</ItemGroup>

</Project>
